# Generated by Django 3.2.9 on 2021-11-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='이름')),
                ('last_name', models.CharField(max_length=100, verbose_name='성')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('e_mail', models.CharField(max_length=100, verbose_name='이메일 주소')),
                ('mobile', models.CharField(max_length=11, verbose_name='연락처')),
                ('comment', models.TextField(max_length=100, verbose_name='소개')),
                ('date', models.DateTimeField(verbose_name='날 짜')),
            ],
        ),
    ]
