# Generated by Django 3.2.9 on 2021-11-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=20)),
                ('dog_size', models.CharField(max_length=20)),
                ('dog_origin', models.CharField(max_length=20)),
                ('dog_explain', models.TextField()),
                ('dog_caution', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
