# Generated by Django 3.2.9 on 2021-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='constellation/post/%Y/%m/%d')),
                ('fortune', models.TextField(blank=True)),
                ('month', models.IntegerField(db_index=True)),
                ('day', models.IntegerField(db_index=True)),
            ],
            options={
                'verbose_name': '별자리',
                'verbose_name_plural': '별자리 목록',
            },
        ),
    ]
