# Generated by Django 3.2.9 on 2021-11-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
    ]
